/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.backend;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        BackendApplication classUnderTest = new BackendApplication();
        assertNotNull(classUnderTest, "app should be created");
    }
}
